FROM golang:1.23.1 AS builder
RUN go install github.com/a-h/templ/cmd/templ@v0.3.833
WORKDIR /go/src/soko
COPY . /go/src/soko
RUN touch assets/keep && templ generate && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o bin .


FROM ghcr.io/pkgcore/pkgcheck:latest
COPY --from=builder /go/src/soko/bin /go/src/soko/bin
WORKDIR /go/src/soko
ENTRYPOINT ["/go/src/soko/bin/update.sh"]
